- lib/AppInfo/BootstrapSingleton.php
- lib/Listener/LoginNotificationListener.php
Else the event doesn't get properly triggered of course since the file
can't be found to autoload.
Seems we merged to fast ;)
> Use the correct namespaces

- lib/Db/SuspiciousLoginMapper.php
- lib/Service/LoginClassifier.php
- tests/Unit/Service/LoginClassifierTest.php
Fixes https://github.com/nextcloud/suspicious_login/issues/115
> Add simple peak detection

- appinfo/info.xml
- lib/Db/SuspiciousLogin.php
- lib/Migration/Version2Date20190913144908.php
- lib/Service/LoginClassifier.php
- lib/Service/NotificationState.php
This should help debug accounts where lots of notifications are sent, even though we now have peak detection.
> Persist the notification state of suspsicious login detections

- README.md
The address of the `git clone`-command in the README file referred to another project, this pull request changes this address to this repository.
> README.md: Fixed git clone command

- lib/Listener/LoginListener.php
- tests/Unit/Listener/LoginListenerTest.php
Regression introduced with https://github.com/nextcloud/suspicious_login/commit/e342d290286f123ef584cb5b2dd020580db2f8fa#diff-030c80dadb86b0a658dcf12b4b194f57. This change removed the collection of token login data, hence very little data was collected and the results suffered -> #181.
Fixes #181
> Always collect token login data

- lib/BackgroundJob/TrainJobIpV4.php
- lib/BackgroundJob/TrainJobIpV6.php
- lib/Command/Optimize.php
- lib/Command/Train.php
- lib/Service/DataLoader.php
- lib/Service/EstimatorService.php
- lib/Service/MLP/Config.php
- lib/Service/MLP/OptimizerService.php
- lib/Service/MLP/Trainer.php
- lib/Service/ModelStore.php
- lib/Service/TrainService.php
- lib/Service/TrainingDataSet.php
- lib/Service/TrainingResult.php
This moves code around into better fitting spots that I'll need for a few upcoming optimizations.
The only change is that the optimize process now operates on a single set of data instead of re-reading the latest data for every batch run. That will make the model comparison fairer.
The app now has three high level services
* Train service: transforms collected data into a model
+ Load data sets
+ Train a classifier
+ Persist the model
* Optimizer: find the best parameters for a given data set
+ Load data sets (but just once, so every training is comparable)
+ Train a bunch of classifiers
+ Print the results (but don't persist anything as this services is meant to find the best parameters, not model)
* Estimator: predict the suspiciousness of a given (UID, IP) tuple
+ Load the latest …
> Organize app into train, optimize and estimator services

- composer.json
- composer.lock
- lib/Command/Optimize.php
- lib/Service/MLP/Config.php
- lib/Service/MLP/OptimizerService.php
- lib/Task/TrainTask.php
Instead of running each parameter set through the trainer x times in series we can run this step in parallel. That means we get a speedup of 5x (that was the old number of runs per parameter set). Now the optimization even runs 8 jobs in each step to gain some precision.
Some technical insight: amphp has an async event queue and allows us to spawn any blocking *task*. This task is a small class that gets deserialized in the main process and deserialized in a spawned worker process. So for 8 training runs we'll have a total of 9 php processes. This is a poor person's replacement for threads in php. Nevertheless the overhead of separate processes shouldn't bother us here for a task that runs several minutes.
> Run the optimization truly parallel

- composer.lock
- lib/Service/DataLoader.php
- lib/Service/NegativeSampleGenerator.php
- tests/Unit/Service/LoginClassifierTest.php
- tests/Unit/Service/NegativeSampleGeneratorTest.php
Turns out the initial implementation of the algorithm invoked the wrong
method for shuffled data generation and therefore random samples were
used for what was believed to be shuffled.
:shrug:
> Use actually shuffled data for shuffled samples

- lib/Service/MLP/OptimizerService.php
- lib/Service/MLP/Trainer.php
- lib/Service/TrainingResult.php
- lib/Task/TrainTask.php
The optimization trains the with the exact same parameters for 8 times to get an average performance estimation of the model. Before this patch there was one summary of the current *cost* (metric that tells how well a model performs) across all training results. Now it prints all results to give some insight into how similar or different the individual results are.
I've tested this all manually. I just need a reviewer for a sanity check :handshake:
> Print all individual optimizer results

- lib/Service/AClassificationStrategy.php
- lib/Service/DataLoader.php
- lib/Service/IpV6Strategy.php
- lib/Service/Ipv4Strategy.php
In the *data loader* the validation threshold and the maximum age timestamps were mixed up. But the same also happened in the classification strategies. So in sum everything gave the correct result, but the naming is confused in both classes.
> Fix (double) variable mix-up

- lib/Command/Optimize.php
- lib/Command/Train.php
- lib/Service/MLP/OptimizerService.php
- lib/Service/TrainingDataConfig.php
During development I test training on data from production instances. As
time is important for the data sets, e.g. to split between historic and
recent data, these data sets get outdated really quick. In order to be
able to still use slightly older data for development and optimization,
this adds a parameter to specify the *current time*.
> Allow time warps

- lib/Service/MLP/OptimizerService.php
It turned out that for some parameters we should allow more extreme
values as they seem to perform a tad better than with the restrictions
of the old ranges.
This update also brought me to https://github.com/nextcloud/suspicious_login/pull/390.
> Update allowed parameter ranges for MLP optimizations

- lib/Service/MLP/Trainer.php
In order to specify the number of epochs I needed to pass a value for *alpha*. As I currently don't understand the important or range of the parameter I'm reverting to the default value of 1e-4 that is used in the original constructor. Changing the value was actually never intended, I must have made a typo.
> Return to the default "alpha" of rubix-ml's MLP

- lib/Command/Optimize.php
- lib/Command/Train.php
- lib/Service/CollectedData.php
- lib/Service/DataLoader.php
- lib/Service/MLP/OptimizerService.php
- lib/Service/TrainService.php
- lib/Task/TrainTask.php
* Do not run into php max execution time
* Read collected DB data once, generate random negatives samples for
every training run.
* Generate negative data in each task so it's run in parallel
* Fix the optimizer algorithm to always test the *next* config and not
the current one. Without this patch the optimizer re-evaluated the
already known "best" config and then picks the new random neighbor as
better -> leading nowhere.
> Fix and improve the MLP optimizer

- lib/Migration/Version0Date20181214083108.php
Specific environments run into SQL errors otherwise where the default is
set to 'NULL' rather than NULL.
Faulty SQL before
```sql
ALTER TABLE oc_suspicious_login_model change `type` type varchar(128) DEFAULT 'NULL' COLLATE utf8mb4_bin,
change `learning_rate` learning_rate         numeric(10, 5) DEFAULT 'NULL',
change `precision_y` precision_y             numeric(10, 5) DEFAULT 'NULL',
change `precision_n` precision_n             numeric(10, 5) DEFAULT 'NULL',
change `recall_y` recall_y                   numeric(10, 5) DEFAULT 'NULL',
change `recall_n` recall_n                   numeric(10, 5) DEFAULT 'NULL'); 
```
> Explicitly set defaults to null during migrations

- composer.json
- composer.lock
2.0 is buggy and rubix doesn't allow us to update. Rubix 1.x has a newer version but requires a retrained model. This again needs a breaking change (major version) here so admins see the critical jump and run the training right after the app update.
Once https://github.com/RubixML/ML/pull/261 is in we can switch back to the original rubix.
I have tested upgrade compatibility by training a model with the old version, then upgrading and using the same model for prediction. That works flawlessly.
> Bump league/flysystem from 2.0.8 to 2.5.0

- renovate.json
Enables https://docs.renovatebot.com/configuration-options/#osvvulnerabilityalerts. This works for stable* branches too.
> chore(deps): Enable osv alerts for renovate

- renovate.json
The default schedule is to only bump on the first day of the month.
> chore(deps): Overwrite schedule for vulnerability updates

- renovate.json
… and update them on stable branches as well (e.g. the outdated and failing xmlling action)
> chore(deps): Enable bumps and pins for github actions

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
Ensures this shipped app doesn't show with a dev suffix when 28 is released.
> chore(release): v6.0.0

- README.md
Fixes https://github.com/nextcloud/suspicious_login/issues/827
> doc: Document installation and distribution

- composer.json
- composer.lock
- lib/Service/IpV6Strategy.php
Fix #837
Fix https://github.com/nextcloud/server/issues/43157
Parse IPv6 addresses directly using built-in functions. I compared both binary representations of hundreds of random IPv6 addresses and they are exactly the same so we don't need to drop trained models.
Ref https://www.php.net/manual/en/function.inet-pton.php
---
Can be tested via:
```
occ suspiciouslogin:seed --v6
occ suspiciouslogin:train --v6
```
> fix(32bit): drop darsyn/ip dependency

- .github/workflows/profile.yml
Manual backport of https://github.com/nextcloud/suspicious_login/pull/852.
> [stable27] ci: Profile with v6 addresses too

- .github/workflows/block-merge-freeze.yml
- .github/workflows/command-compile.yml
- .github/workflows/node.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/pr-feedback.yml
- .github/workflows/profile.yml
- .github/workflows/test.yml
> ci: update workflows from templates

- README.md
> fix: Add geo/ISP lookup button config option to README

- README.md
Addresses https://github.com/nextcloud/suspicious_login/pull/872#discussion_r1597565497 by making it clear what the default is and how to disable if desired.
> fix(README): Adjust IP lookup instructions to match default

- lib/Listener/LoginMailListener.php
- lib/Notifications/Notifier.php
Fixes https://github.com/nextcloud/suspicious_login/issues/891
> feat: Improved email and notification text

- lib/Notifications/Notifier.php
Fixes https://github.com/nextcloud/suspicious_login/issues/910
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/1e2c799b-e3de-4a58-81be-558f5f27866f) | ![image](https://github.com/user-attachments/assets/705fea7a-d20b-4379-a5a9-b423f77a5d76) |
> fix: inverted logo in notification

- lib/BackgroundJob/TrainJobIpV4.php
- lib/BackgroundJob/TrainJobIpV6.php
- lib/Listener/LoginMailListener.php
- lib/Listener/LoginNotificationListener.php
- lib/Service/ETLService.php
- lib/Service/EstimatorService.php
- lib/Service/LoginClassifier.php
- lib/Service/ModelStore.php
- tests/Unit/Service/LoginClassifierTest.php
> fix: Replace deprecated ILogger with Psr\Log\LoggerInterface

- lib/Service/LoginClassifier.php
While #152 addressed rate limiting notifications to users, we still have some logging outside of there that isn't covered.
* Adjusts log levels (Warning -> a mixture of Debug and Info) of the two main messages that aren't rate limited
* Adjusts log levels of the already rate limited messages to Info level (from Warning) to be more consistent with Brute Force Protection log levels
This cuts down on the log noise from "Detected a login from a suspicious login..." 
All logs remain available at the appropriate log levels if desired.
Fixes #303
> fix(LoginClassifier): Adjust log levels / reduce logging noise

- lib/Service/NegativeSampleGenerator.php
- tests/Unit/Service/NegativeSampleGeneratorTest.php
To weight the usage of IPs in the data model, the user id is being added multiple times to the dataset. The exact number is being determined here: https://github.com/nextcloud/suspicious_login/blob/9043a660450844656d5bc63c6909242809003976/lib/Service/DataLoader.php#L80
The problem is that this isn't always being taken into account when generating the training data. In case the dataset contains no IP with *exactly* one user id in the array, the array is malformed by containing *only* user ids (16 columns in size) in this variable: https://github.com/nextcloud/suspicious_login/blob/9043a660450844656d5bc63c6909242809003976/lib/Service/DataLoader.php#L107
The reason is the code in the [`getUniqueIPsPerUser` function](https://github.com/nextcloud/suspicious_login/blob/9043a660450844656d5bc63c69 …
> fix(NegativeSampleGenerator): Prevent duplicate user IDs when getting unique IPs

- tests/bootstrap.php
Tests fail right now. This might be the reason, because Nextcloud complains that config.php is not in the right format.
> test: Set PHPUNIT_RUN env var

- lib/Db/LoginAddressAggregatedMapper.php
- lib/Service/DataLoader.php
On medium and large installations there can be a lot of login data. Loading it can exhaust the available PHP memory.
This limits the impact in two steps
1. Limit number of DB rows read
2. Limit number of datasets generated from DB results (DB results are deduplicated and we re-duplicate in memory)
master: I was not able to run ``occ suspiciouslogin:train --v6 --dry-run -vvv`` with a memory limit of 512M (Nextcloud default)
here: I can run ``occ suspiciouslogin:train --v6 --dry-run -vvv`` successfully with a memory limit of 256M
> fix: try to avoid memory exhaustion

- composer.json
- composer.lock
Tested training a model with 2.3 and predicting with 2.5 -> works :heavy_check_mark: 
It seems I accidentally pinned 2.3 at the last upgrade, so renovate didn't open an automated update.
> fix(deps): Update rubix/ml to v2.5

- .nextcloudignore
Reduce the size of release artifacts.
Remove 27M (2.9M compressed) from the release artifact.
> fix: exclude vendor-bin from release artifacts

- .github/workflows/phpunit-mariadb.yml
- .github/workflows/profile.yml
Supersedes https://github.com/nextcloud/suspicious_login/pull/954
> ci: test against MariaDB 11.4 (too)

- lib/Db/Model.php
- lib/Service/Statistics/AppStatistics.php
- lib/Service/Statistics/TrainingDataStatistics.php
- lib/Service/TrainingDataConfig.php
Fixes 
```
> phpunit -c tests/phpunit.xml tests/Unit
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.2.28
Configuration: tests/phpunit.xml
Warning:       No code coverage driver available
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
PHP Fatal error:  During inheritance of JsonSerializable: Uncaught Return type of OCA\SuspiciousLogin\Service\Statistics\TrainingDataStatistics::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
/home/runner/work/suspicious_login/suspicious_login/apps/suspicious_login/lib/Service/Statistics/Trai …
```
> fix(php): suppress notice of JsonSerializable::jsonSerialize

- lib/Command/Predict.php
- lib/Exception/ModelNotFoundException.php
- lib/Service/EstimatorService.php
- lib/Service/LoginClassifier.php
- lib/Service/ModelStore.php
This PR aims to fix #793.
I've separated the fact that a model could not be found from the other possible service exceptions. When such a case is found, it now only logs to the debug log. This might technically be duplicate, but I think it's good to include anyways for debugging purposes.
> Reduce log messages when no model found

- .github/workflows/lint-info-xml.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/lint-php.yml
In the latest pull requests, the pipeline for linting the PHP code fails as it wants to run against PHP 8.4 (see https://github.com/nextcloud/coding-standard/issues/47).
One of the comments there recommend to update the workflow template, which this pull request does. I guess the main change is the use of `steps.versions.outputs.php-min` instead of `steps.versions.outputs.php-available`. This means it should always run with the lowest supported PHP version.
The other workflows differ from the template repository as well (e.g. different database versions on phpunit workflows), but I didn't want to change too much here.
> chore: Update workflow templates for `lint-info-xml`, `lint-php-cs` and `lint-php`

- lib/Service/NegativeSampleGenerator.php
- lib/Service/Statistics/AppStatistics.php
- tests/Unit/Service/NegativeSampleGeneratorTest.php
Generating shuffled samples is based on IP addresses which are used exclusively by one user. If no user has such an unique IP address, the returned DataSet object contains no IP address at all. This results in an exception during merge with the "regular" DataSet objects due to the different length.
To mitigate this, I now return an empty `Labeled()` object which can be used in the `merge` function of RubixML without any issues. Additionally, I revert the change from #810 as `generateFromRealData` shouldn't be called without any unique IPs at all. I suspect that all people in #745 are affected by this bug in the first place and experience the error from #860 now.
This should fix the latest reports in #860.
> Fix too short DataSet for shuffled samples when there is no unique IP address

- composer.json
- composer.lock
- lib/Service/Statistics/AppStatistics.php
As discussed in #1017, `php-stemmer` is a dependency of RubixML. They currently point to the version 3.0 of `php-stemmer`, which isn't fully compatible with PHP 8.4 due to a dependency on `portable-utf8`, which isn't that well maintained anyway. This issue is already handled by the maintainers of `php-stemmer` by releasing the version 4.0, which replaced `portable-utf8` with `joomla/string`. This isn't a breaking change, so, the version bump was done just in case.
Until RubixML uses the latest version (see https://github.com/RubixML/ML/issues/359), we can deploy a workaround and use `php-stemmer` 4.0 by using it as alias for version 3.0.
This fixes #1017.
> Update php-stemmer to 4.0 as workaround for full PHP 8.4 compatibility
