nextcloud/suspicious_login

- tests/Unit/Service/AdminServiceTest.php
> Unit test the admin service

- tests/Unit/Settings/AdminSettingsTest.php
> Unit test the admin settings class

- tests/Unit/Util/AddressClassifierTest.php
> Unit test the address classifier

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
[Release checklist](https://blog.wuc.me/2018/08/14/nextcloud-app-release-process.html):
> Release v1.0.0

- .travis.yml
- CHANGELOG.md
- appinfo/info.xml
- lib/AppInfo/BootstrapSingleton.php
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>
> 17 only version

- lib/AppInfo/BootstrapSingleton.php
- lib/Notifications/Notifier.php
> Adjust notifier to Nextcloud 17

- lib/Service/EstimatorService.php
- lib/Service/ModelPersistenceService.php
Test package: [suspicious_login.tar.gz](https://github.com/nextcloud/suspicious_login/files/3279779/suspicious_login.tar.gz)
> Handle deserialization errors better

- lib/AppInfo/BootstrapSingleton.php
- lib/Event/SuspiciousLoginEvent.php
- lib/Listener/LoginNotificationListener.php
- lib/Service/LoginClassifier.php
In preparation to send e-mails as well having a more event based
appraoch is cleaner IMO.
Then we could also chose to add them as activities in a later stage etc.
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>
> Move to events

- lib/AppInfo/BootstrapSingleton.php
- lib/Listener/LoginMailListener.php
Fixes #48
TODO:
-  ~~Maybe add cli command to properly test~~
> Also send a mail on a suspicious login event

- lib/AppInfo/BootstrapSingleton.php
- lib/Event/PostLoginEvent.php
- lib/Listener/LoginListener.php
Related to https://github.com/nextcloud/server/pull/16579, but that event is not in the public API yet, so building my own.
> Use a PostLoginEvent for the login listener

- lib/Service/ETLService.php
Fixes #89
Two changes now: 
- Changed way to insert or update logins from `try{insert}catch(exception){update)` to `if(is null select){insert}else{update}`
- `fetch()` doesn't produce any results so using `fetchAll()` instead.
This time it's working on my setup, populates `login_address_aggregated` with data
> Sorted issue with PostgreSQL

- lib/Command/Optimize.php
- lib/Service/MLP/Optimizer.php
Fixes https://github.com/nextcloud/suspicious_login/issues/188.
> Fix optimizer params and add ipv6 support

- lib/Service/ModelPersistenceService.php
Fixes 
cc @adi-dev @Zocker1999NET @GrillGuth
> Fix parameter type of model files

- composer.json
- composer.lock
Fixes https://github.com/nextcloud/suspicious_login/issues/317
Test build: [suspicious_login.tar.gz](https://github.com/nextcloud/suspicious_login/files/5161280/suspicious_login.tar.gz)
> Remove coding standard dependency from production build

- lib/Service/MLP/Config.php
This is the result of hammering eight CPU cores for a full weekend.
> Update default MLP parameters

- lib/Command/Train.php
Tiny regression from https://github.com/nextcloud/suspicious_login/pull/383: the occ train command didn't persist anymore. As admin you still want to run this, e.g. after an app update. Nevertheless there is now also a `--dry-run` option to only train and don't persist.
> Persist CLI training results

- .github/workflows/profile.yml
- lib/Service/MLP/Trainer.php
precision=precision
recall=recall
it's that simple. yet I've mixed it up.
> Fix mixed up model stats

- package-lock.json
- package.json
> Use @nextcloud/browserslist-config

- img/app.svg
- lib/Notifications/Notifier.php
Fix #212
Disclaimer: I could not test this because I cannot compile the app. See https://github.com/nextcloud/suspicious_login/issues/536 
Signed-off-by: szaimen <szaimen@e.mail.de>
> add icon to notification

- lib/Notifications/Notifier.php
Fix #209
Disclaimer: I could not test this because I cannot compile the app. See https://github.com/nextcloud/suspicious_login/issues/536 
Signed-off-by: szaimen <szaimen@e.mail.de>
> add button to notification for more info about the suspicious ip

- .github/workflows/profile.yml
Ref https://github.com/nextcloud/server/issues/25436
Nextcloud doesn't work with 10.6 yet.
> Downgrade to MariaDB 10.5 on CI

- lib/Notifications/Notifier.php
```
Exception: Class 'OCA\SuspiciousLogin\Notifications\IAction' not found in file '/var/www/html/apps/suspicious_login/lib/Notifications/Notifier.php' line 93
```
> Fix missing import

- .github/workflows/lint.yml
- .github/workflows/test.yml
- appinfo/info.xml
> Update master php testing versions

- .github/workflows/test.yml
1) The app code checker is dead
2) The workflow workaround is not needed anymore
> Remove Nextcloud 20 remnants

- .github/workflows/build.yml
> Only install LTS node and use `npm ci`

- .github/workflows/profile.yml
- .github/workflows/test.yml
- appinfo/info.xml
- composer.json
- composer.lock
More Nextcloud versions tested but fewer CI jobs.
> Allow PHP8.1

- .github/workflows/test.yml
- appinfo/info.xml
> Drop Nextcloud 21 support

- lib/BackgroundJob/TrainJobIpV4.php
- lib/BackgroundJob/TrainJobIpV6.php
Fixes https://github.com/nextcloud/suspicious_login/issues/608
> Make training jobs time insensitive

- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/test.yml
- appinfo/info.xml
- doc/stats.md
- lib/Db/LoginAddressAggregatedMapper.php
- lib/Migration/Version0Date20190115134303.php
- lib/Migration/Version4002Date20220922094803.php
- lib/Migration/Version4002Date20220922094804.php
- lib/Service/ETLService.php
Backport of https://github.com/nextcloud/suspicious_login/pull/699
> [stable25] Add sqlite and oci compatibility

- appinfo/info.xml
> [stable25] ensure that version is not below than released on the appstore

- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/test.yml
> Adjust testing matrix for Nextcloud 25 on stable25

- .github/workflows/lint.yml
- .github/workflows/profile.yml
- .github/workflows/test.yml
Port of https://github.com/nextcloud/suspicious_login/pull/714.
> [stable25] Do not test against server master

- lib/Command/ETL.php
- lib/Command/Optimize.php
- lib/Command/Predict.php
- lib/Command/Seed.php
- lib/Command/Train.php
Backport of a fix I accidentally pushed to master directly.
> [stable25] Add return type hints for occ commands

- appinfo/info.xml
- package-lock.json
- package.json
> feat(deps)!: Add Nextcloud 27 support

- renovate.json
https://github.com/nextcloud/suspicious_login/pull/784 and https://github.com/nextcloud/suspicious_login/pull/786 failed
> chore(deps): Group AMPHP package updates

- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/test.yml
> chore(CI): Adjust testing matrix for Nextcloud 27 on stable27

- appinfo/info.xml
- package-lock.json
- package.json
> feat(deps): Add Nextcloud 28 support on master

- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/profile.yml
- .github/workflows/test.yml
> chore(CI): Adjust testing matrix for Nextcloud 26 on stable26

- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
As requested by @ChristophWurst [here](https://github.com/nextcloud/suspicious_login/pull/729#pullrequestreview-1143602047), [here](https://github.com/nextcloud/suspicious_login/pull/730#pullrequestreview-1143602634) and [here](https://github.com/nextcloud/suspicious_login/pull/731#pullrequestreview-1143603001).
The other issue is not valid anymore as the test invocation was already fixed by #802.
> ci(phpunit): revert force enabling the app

- .github/workflows/phpunit-mysql.yml
- appinfo/info.xml
- package-lock.json
- package.json
- renovate.json
> feat(deps): Add Nextcloud 29 support on master

- .github/workflows/profile.yml
Manual backport of https://github.com/nextcloud/suspicious_login/pull/852.
> [stable26] ci: Profile with v6 addresses too

- .github/workflows/profile.yml
Manual backport of https://github.com/nextcloud/suspicious_login/pull/852.
> [stable28] ci: Profile with v6 addresses too

- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/profile.yml
- .github/workflows/test.yml
> chore(CI): Adjust testing matrix for Nextcloud 29 on stable29

- lib/Listener/LoginMailListener.php
Fixes #801
Relies on existing app config parameter already used for toggling in-app notifications.
> feat(suspicious_login): Add "more info" button to email notifications

- .github/workflows/npm-audit-fix.yml
Not sure anything beyond the GH action is needed in terms of setup on the repo itself @ChristophWurst
> Add npm audit fix job

- composer.json
- composer.lock
- vendor-bin/php-cs-fixer/composer.lock
Ref https://github.com/nextcloud/suspicious_login/commit/8daf1c106428e441aafe8af6261a8d132285a4dd#r145083705
> chore: move composer-bin-plugin to prod dependencies

- lib/Service/MLP/OptimizerService.php
Fixes https://github.com/nextcloud/suspicious_login/issues/902
> fix(php): Make OptimizerService::optimize nullalble param required

- .github/workflows/npm-audit-fix.yml
- appinfo/info.xml
- package-lock.json
- package.json
- renovate.json
> feat(deps): Add Nextcloud 31 support on master

- .github/workflows/profile.yml
- .github/workflows/test.yml
> chore(CI): Adjust testing matrix for Nextcloud 30 on stable30

- .github/workflows/command-compile.yml
> ci: Update workflows

- composer.lock
This dev dependency is vulnerable
> fix(deps): Bump symfony/process

- composer.lock
Manual backport of https://github.com/nextcloud/suspicious_login/pull/956
> [stable30] fix(deps): Bump symfony/process

- composer.lock
Manual backport of https://github.com/nextcloud/suspicious_login/pull/956
> [stable29] fix(deps): Bump symfony/process

- appinfo/info.xml
- composer.json
- composer.lock
- lib/BackgroundJob/TrainIpV4OnceJob.php
- lib/BackgroundJob/TrainIpV6OnceJob.php
- lib/Migration/Version9000Date20250114095826.php
- lib/Service/ModelStore.php
- lib/Service/TrainingResult.php
Fixes https://github.com/nextcloud/suspicious_login/issues/946
> fix(deps): Make psr/log:3 compatible by rubix upgrade

- .github/workflows/npm-audit-fix.yml
- appinfo/info.xml
- renovate.json
> feat(deps): Add Nextcloud 32 support on master

- vendor-bin/phpunit/composer.json
- vendor-bin/phpunit/composer.lock
This currently breaks master daily builds
> ci(phpunit): Make sure to be PHP 8.1 compatible

- composer.lock
stable31 variant/backport of https://github.com/nextcloud/suspicious_login/pull/1014
> [stable31] fix(deps): bump amphp/parallel to v1.4.4. for PHP8.4 compatibility

- .github/workflows/npm-audit-fix.yml
- appinfo/info.xml
- renovate.json
> feat(deps): Add Nextcloud 33 support on master

- package-lock.json
> [stable30] fix(deps): update cross-spawn to v7.0.6
